### ISSUE TITLE
Invalid results of the function GetAttributeFromHeader in System.Web.HttpRequest

### ISSUE THREAD

**Issue by chessar** [Microsoft/referencesource#32]
https://github.com/Microsoft/referencesource/blob/455f59f089ff2e96375e800c9b7866446f16cb30/System.Web/HttpRequest.cs#L823

https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/HttpListenerRequest.cs#L1216

For example, for parameters
headerValue = `"multipart/form-data; boundary=abc; charset=UTF-8"`  (from Content-Type header) and 
attrName = `"boundary"`
The result will be
> **"abc;"**

instead

> **"abc"**

In this case, the [Files](https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpRequest.cs#L2388) and [Form](https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpRequest.cs#L2164) collections are empty, because boundary value (from [GetMultipartBoundary](https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpRequest.cs#L1079)) is not valid.

**Comment by karelz** [comment]
Please file the issue on VS Developer Community portal: https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback
I assume there are 2 different problems - in HttpListener and in System.Web.HttpRequest. Can you please sketch a repro & impact of each in your report? Note: Unless the impact is high (incl. additional upvotes), it may not meet the bar for a fix in .NET Framework.

We should close the issue here (sadly, I don't have permissions to do that).

**Comment by chessar** [comment]
Hello, @karelz 

>Please file the issue on VS Developer Community portal: https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback

I posted a report on VS Developer Community portal:
https://developercommunity.visualstudio.com/content/problem/302929/invalid-results-of-the-function-getattributefromhe.html
