### ISSUE TITLE
ResourceReader Cannot Read Resource File

### ISSUE THREAD

**Issue by zeus82** [Microsoft/referencesource#57]
We are in the process of migrating an application from the .NET Framework to .NET Core 2, but it looks like the ResourceReader cannot process a valid resx file.

When I create the ResourceReader I get 

```
System.ArgumentException: Stream is not a valid resource file.
   at System.Resources.ResourceReader._ReadResources()
   at System.Resources.ResourceReader.ReadResources()
   at System.Resources.ResourceReader..ctor(String fileName)
```

Here is a [gist](https://gist.github.com/zeus82/e45838a029f58784ebe2e118b11f21cf) to the contents of the resx file.

**Comment by svick** [comment]
This repository hosts the reference source for .Net Framework and is not for reporting issues with .Net Core. Can you close the issue here and reopen it [in the coreclr repo](https://github.com/dotnet/coreclr), which is where [the source for the .Net Core version of `ResourceReader`](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Resources/ResourceReader.cs) is located?

**Comment by zeus82** [comment]
Done.  Here is the new issue: https://github.com/dotnet/coreclr/issues/17946

Thanks.
